### ISSUE TITLE
優化：獲取所有和最新照片   相冊為空的時候處理

### ISSUE THREAD

**Issue by NetaGuo** [liuling07/PhotoPicker#12]
拍照完畢通知系統相冊更新：context.sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.parse("file://" + path)));
獲取手機内部所有圖片 :Cursor mCursor = mContentResolver.query(imageUri,null, null,null,Media.DATE_ADDED+" desc");
遍歷相冊的時候：用do{} while（）；結構，確保獲取第一個
相冊為空時候：if (!mCursor.moveToFirst()){     mCursor.close();  return floderMap;} 游標是否爲空  相應的地方均要做判空處理

**Comment by liuling07** [comment]
已经处理了，多谢反馈。
