### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by LiJia92** [liuling07/PhotoPicker#2]
![qq 20160113100413](https://cloud.githubusercontent.com/assets/11539173/12282908/06e025fc-b9dd-11e5-9c59-f0485d7c9bb0.png)
加载正常图片没问题，但是在加载（微博）长图，例如439*4268px这种尺寸的图，就会报内存溢出了。

**Comment by liuling07** [comment]
你的是什么型号手机？ 我从微薄弄了张440*5420px的长图都没有OOM。
